.MODEL TINY
.486
.DATA
ORG 1000H
COUNT1 DW 0000H
DAT1DB -1
DAT2	DB -1                                     ;INTERFACING CIRCUTARY
1.8086 TO 8255-INITIALISATION OF 8255.
DISP1 DW 'FULL'
DISP2 DW 'EMPTY'
STORE DB 00H

.CODE
.STARTUP
	MOV AL,90H
	OUT 06H,AL			;CONTROL WORD OF 8255
	
LCD INITIALISATIONS DISPLAY:
	MOV	AL,30H		;REPEAT THIS FOR 4 TIMES
	CALL OUTCMD
	CALL DELAY41		;WAIT FOR 4.1 MS ATLEAST
	MOV	AL,30H		;SECOND TIME
	CALL	OUTCMD		;BUS FLAG STATUS CANNOT BE CHECKED 
	MOV	AL,30H		;IN THIS TIME
	CALL OUTCMD
	
	MOV	AL,00110000B
	CALL OUTCMD
	NOP				           ;CALL DELAY100
	MOV	AL,08H                        ;DISPLAY OFF
	CALL OUTCMD
	MOV	AL,01H                        ;CLEAR DISPLAY
	CALL OUTCMD
	MOV	AL,0CH		;DISP ON
	CALL OUTCMD
	MOV	AL,06H		;AUTOINCREMENT.SHIFT CURSOR
          CALL OUTCMD
X:	CALL LCD
	IN AL,00H
	AND AL,30H	
	CMP AL,00H		;CHECKING FOR THE REMOTE
	JZ X
 MOV AL,80H		;GIVING THE DIR TO MOTOR AND THE
ENABLE


SIGNAL  FOR  THE TIMER  (SENDING SIGNAL TO MOTOR VIA PORTC.CONNECT PORTC TO MOTOR ENABLE SIGNALS AND GIVE PROPER DELAY AS PER THE CLOCK PROVIDED OF 10KHZ FROM 8086 INTERFACE)
	
OUT 04H,AL
	     CALL MOTOR           ;OPENING THE GARAGE
X1:	IN AL,00H
	AND AL,0C0H
	CMP AL,80H		;CHECKING FOR THE IR SENSORS , WE 
                                                   WILL BE LOOKING FOR PORTC PIN 6,7 AND 
THEY ARE GOING TO BE CONNECTED TO
	                                        SWITCHES I/P WILL BE GIVEN TO MOTOR  
                                                   ENABLE SIGNAL SO THAT MOTOR WORKS
                                                   FOR EVERY SWITCH PRESSED, EITHER FOR
                                                   EXIT OR ENTRY
JZ ENTRY
	CMP AL,40H
	JZ EXIT
	JMP X1
ENTRY:CMP DAT2,-1
	JNZ X2
	IN AL,00H
	AND AL,08H		 ;CHECKING FOR THE PRESSURE 
                                                      TRANSDUCER, 0000 1000
CMP AL,08H
	JNZ X2
	INC DAT2
X2:	IN AL,00H
	AND AL,40H
	CMP AL,40H		;CHECKING FOR THE ENTRY OF CAR INTO 
                                                     GARAGE
	JNZ ENTRY
	CMP DAT1,0
	JNZ X3
	INC COUNT1
	MOV DAT1,-1
X3:	IN AL,00H
	AND AL,0F8H		;WAITNG TILL THE CAR HAS 
                                                                ENTERED
	CMP AL,00H
	JNZ X3
	     CALL DELAY_5MIN	; CALLING A DELAY OF 5 MIN
CMP DAT2,0OH		;CHECKS WHETHER A CAR HAS 
           ENTERED IN THIS SPAN OF 5 MIN                                                                              
	JZ X1
	JMP X
EXIT:	CMP DAT2,-1
	JNZ X4
	IN AL,00H
	AND AL,08H		;CHECKING FOR THE PRESSURE 
                                                               TRANSDUCER
	CMP AL,08H
	JNZ X2
	DEC DAT2
X4:	IN AL,00H
	AND AL,80H
	CMP AL,80H		;CHECKING FOR THE EXIT FROM THE 
                                                               GARAGE
	JNZ EXIT
	CMP DAT2,0
	JNZ X5
	INC COUNT1
	MOV DAT2,-1
X5:	IN AL,00H
	AND AL,0F8H
	CMP AL,0
	JNZ X5
	CALL DELAY_5MIN		;CALLING A DELAY OF 5 MIN
	
CMP DAT2,00H		;CHECKS WHETHER A CAR HAS 
                                                                  ENTERED IN THIS SPAN OF TIME
JZ X1
	JMP X	

OUTCMD:	
	           PUSH AX
	           MOV AL,80H			
		OUT	06H,AL
		POP	AX
		OUT	02H,AL
		MOV	AL,4
		OUT	04H,AL
		NOP
		NOP
		MOV	AL,0
		OUT	DX,AL
		CALL	DELAY41
		RET
	

MOTOR :	
	MOV AL,36H		;SETTING THE MODE OF COUNTER0 TO MODE 3>>>>>> AT 8254, SET CNT0 FROM CNTROLREGISTER
	OUT 0EH,AL
	MOV AL,5AH
	OUT 08H,AL		;INITIALIZING THE COUNTER0 WITH 2650, 
PUT VALUE 0A5AH IN CNTER0 VIA 
                                                     INSTRUCTIONS
	MOV AL,0AH
	OUT 08H,AL
	MOV AL,54H		;SETTING THE MODE OF COUNTER1 TO
                                                     MODE 2, INITIALISE COUNTER2 OF 8254

	OUT 0EH,AL
	MOV AL,05H		;SETTING THE COUNTER1 WITH 5,PUT 5 IN
                                                     CONTER1, PROGRAM COUNTER 1BY 
                                                     PUTTING AL=5, HERE WE ARE GIVING A 
                                                    CLOCK TO MOTOR BY 8254
	OUT 0AH,AL
	CALL DELAY_30S
	RET
DELAY_5MIN:	
	MOV CX,0FFFFH
	MOV DAT2,-1
	MOV DX,349
Y:	NOP 
	NOP
	IN AL,00H
	MOV BL,AL
	AND AL,30H		;CHECKS FOR THE PRESSING OF THE 
                                                     REMOTE
	CMP AL,00H
	JNZ Y1
	AND BL,0C0H		
	CMP BL,0		;CHECKING FOR THE ENTRY OF ANOTHER 
                                                      CAR OR MAN
          JNZ Y2
	LOOP Y
	MOV CX,0FFFFH
	DEC DX
	CMP DX,00H
	JNZ Y
Y1:	MOV AL,0C0H
	OUT 04H,AL
	CALL MOTOR		;CLOSING THE GARAGE
	JMP Y3
Y2:	INC DAT2
Y3:
	RET
DELAY_30S:	
D3:	MOV CX,015EAH 
	LOOP D3
	
PROC TO WRITE DATA ON LCD:

	WRITE:	
		MOV	AL,BL		;DATA SEND ON BL
		OUT	02H,AL
		MOV	AL,2
		OUT	04H,AL
		NOP
		NOP
		MOV	AL,06H
		OUT	04H,AL
		NOP
		NOP
		MOV	AL,00H
		OUT 04H,AL
		CALL BUSY
		RET
	
PROC TO TEST BUSY AND RET IF NOT BUSY:

BUSY:
AGAIN:	MOV	AL,92H
		OUT	06H,AL              ;MAKING PORTB INPUT PORT
		MOV	 AL,01H
		OUT	04H,AL
		MOV	AL,05H
		OUT	04H,AL
		NOP
		NOP
		IN AL,02H
		PUSH	AX
		
		MOV	AL,0
		OUT	04H,AL
		MOV	AL,90H
		OUT	06H,AL
		POP AX
		SHL AL,1
		JC AGAIN
		RET
	

PROC FOR CLEAR DISPLAY:

	CLS:	
		MOV	AL,1
		OUT	02H,AL
		MOV  AL,04H
		OUT	04H,AL
		NOP
		NOP
		MOV	AL,00H
		OUT	04H,AL
		CALL DELAY41
		RET
	
PROGRAM STARTS:


LCD :
MOV AX,COUNT1
CMP AX,2000
JNZ X10
CALL FULL
X10:CMP AL,0
JNZ X11
CALL EMPTY
X11:CALL COUNT
RET

COUNT:
	CALL	CLS
	CALL	CENTER
                   MOV CL,04H
	MOV 	DX,COUNT1
X6:	         DIV DL
	MOV	STORE,AL
	MOV	AH,00H
	AAM
	        ADD AL,30H
	        MOV BL,AL
	        CALL WRITE
	        MOV AL,STORE
	LOOP	X6
RET

FULL:
	CALLCLS
	CALL	CENTER	
	MOV	CL,4
	MOV	SI,DISP1
X7:	LODSB
	MOV	BL,AL
	CALL	WRITE
	LOOP	X7
RET

EMPTY:	
	CALL	CLS
	CALL	CENTER
	MOV	CL,5
	MOV	SI,DISP2
X8:	LODSB	
	MOV	BL,AL
	CALL	WRITE
	LOOP	X8
RET
DELAY FOR 4.1 MSEC:
DELAY_4.1MSEC	
MOV CX,80
X9: LOOP X9
RET
COUNTER:	
                  MOV BL,29                             ;PORTB SHOUL HAVE 0010 1001
CALL	WRITE
CALL	WRITE
                  CALL WRITE
                  CALL WRITE
                  CALL	WRITE                        ;CALL WRITE IS WRITTEN HERE 
                                                                    5 TIMES TO WRITE ON EVERY LCD
RET
.EXIT
END

